import { spawn, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { qualifiedDirty, qualifiedSourcePaths } from './source-paths.mjs';
const task = process.argv[2];
const allowed = ['tls:init','test:tls','app:run','app:stop','demo:run','evidence:export','candidate:package','test:lifecycle','install','contracts:generate','contracts:check','typecheck','lint','test','test:f07','test:auth','test:consent','test:expiry','test:enforcement','test:evidence','test:regression','regression:init','regression:run','runtime:build','test:network','test:isolation','dependencies:check','fixture:simulator','fixture:assign','test:workflows','machine:init','roles:init','seed:orders','auth:init','auth:bootstrap','seed:auth','tracking:check','hygiene:check','db:migrate','preflight','services:smoke','web:smoke','build','audit','profile:init','services','reset:bootstrap'];
if (!allowed.includes(task)) throw new Error('Unknown engineering command');
const root = process.cwd();
const sha = input => createHash('sha256').update(input).digest('hex');
const git = args => spawnSync('git', args, { cwd: root, encoding: 'utf8', windowsHide: true }).stdout.trim();
// One qualified inventory for candidate identity and every evidence record.
const files = qualifiedSourcePaths(git(['ls-files','--cached'])).filter(existsSync);
const source = files.map(path => ({path,sha256:sha(readFileSync(path))}));
const dirty = qualifiedDirty(git(['status','--porcelain','--untracked-files=all']));
const contractVersion = JSON.parse(readFileSync('packages/contracts/package.json','utf8')).version;
const started = new Date().toISOString();
const ticket = process.env.ORVIA_TASK_ID ?? 'A00';
if (!/^A0[0-7]$/.test(ticket)) throw new Error('Invalid evidence task');
const prefix = `handoffs/codex/artifacts/${ticket}-${task.replaceAll(':','-')}-${started.replaceAll(':','-')}`;
mkdirSync('handoffs/codex/artifacts',{recursive:true});
const executable = process.platform === 'win32' ? resolve('.local/tools/node-v24.21.0-win-x64/node.exe') : process.execPath;
const pnpm = resolve('.local/tools/package-manager/node_modules/pnpm/bin/pnpm.mjs');
const args = [pnpm,task,...process.argv.slice(3)];
if(process.env.ORVIA_PROFILE==='rehearsal'&&existsSync('.local/profiles/rehearsal/tls/ca-cert.pem'))process.env.NODE_EXTRA_CA_CERTS=resolve('.local/profiles/rehearsal/tls/ca-cert.pem');
const startCommit = git(['rev-parse','HEAD']);
const child = spawn(executable,args,{cwd:root,windowsHide:true,env:{...process.env,PATH:`${resolve('.local/tools/node-v24.21.0-win-x64')}${process.platform==='win32'?';':':'}${process.env.PATH}`,NEXT_TELEMETRY_DISABLED:'1',DO_NOT_TRACK:'1',BETTER_AUTH_TELEMETRY:'0'}});
let output='';
child.stdout.on('data',chunk=>{output+=chunk;process.stdout.write(chunk);});
child.stderr.on('data',chunk=>{output+=chunk;process.stderr.write(chunk);});
child.on('error',error=>{output+=`\nLaunch error: ${error.code}\n`;});
child.on('close',(code,signal)=>{
  writeFileSync(`${prefix}.log`,output,{flag:'wx'});
  const finishedFiles=qualifiedSourcePaths(git(['ls-files','--cached'])).filter(existsSync);
  const finishedSource=finishedFiles.map(path=>({path,sha256:sha(readFileSync(path))}));
  const changed=sha(JSON.stringify(source))!==sha(JSON.stringify(finishedSource));
  const report = {task_id:ticket,test_ids:task==='test:auth'?['T02','T03','T04','T05','T27']:task==='services:smoke'?['T01','T28']:[],command:['node','scripts/record.mjs',...process.argv.slice(2)],cwd:root,started_at:started,finished_at:new Date().toISOString(),exit_code:code,signal,source_commit:startCommit,source_tree_sha256:sha(JSON.stringify(source)),source_files:source,source_changed_during_run:changed,finished_source_tree_sha256:sha(JSON.stringify(finishedSource)),...(changed?{finished_source_files:finishedSource}:{}),dirty,contract_version:contractVersion,profile:process.env.ORVIA_PROFILE??'codex-a00',fixture_id:task==='test:f07'?'W00-F07-provider-receipt':ticket==='A00'?'bootstrap-probe-v1':'aster-birch-v1',result:code===0?'PASS':'FAIL',artifact_paths:[`${prefix}.log`],limitations:['Ticket-scoped engineering evidence only; not full sprint acceptance. Work and human acceptance remain required.','dirty describes source changes; handoff/evidence-only changes are excluded.']};
  writeFileSync(`${prefix}.json`,JSON.stringify(report,null,2)+'\n',{flag:'wx'});
  console.log(`Evidence: ${prefix}.json`);
  process.exitCode=code??1;
});
